config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('content.urls', namespace='content')),
    path('subscription/', include(
        'subscription.urls',
        namespace='subscription')),
    path('product/', include('product.urls', namespace='product'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from content.apps import ContentConfig
from content.views import ContentDetailView, ContentListView, \
    ContentCreateView, ContentUpdateView, IndexView, ContentDeleteView

app_name = ContentConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path(
        'content/<int:pk>/detail/',
        ContentDetailView.as_view(),
        name='content_detail'
    ),
    path(
        'content/',
        ContentListView.as_view(),
        name='content_list'
    ),
    path(
        'content/create/',
        ContentCreateView.as_view(),
        name='content_create'
    ),
    path(
        'content/<int:pk>/update/',
        ContentUpdateView.as_view(),
        name='content_update'
    ),
    path(
        'content/<int:pk>/delete/',
        ContentDeleteView.as_view(),
        name='content_delete'
    )
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import UserRegisterView, LoginView, LogoutView, \
    UserUpdateView, UserDetailView, VerifyView, GetVerify

app_name = UsersConfig.name

urlpatterns = [
    path('<int:pk>/detail/', UserDetailView.as_view(), name='user_detail'),
    path('create/', UserRegisterView.as_view(), name='user_create'),
    path('update/', UserUpdateView.as_view(), name='user_update'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('<int:pk>/verify/', VerifyView.as_view(), name='verify'),
    path('<int:pk>/get/verify/', GetVerify.as_view(), name='get_verify')
]

content/models.py
from django.db import models

from config import settings
from users.models import NULLABLE
from users.services import user_directory_path_content


class Content(models.Model):
    """
    Модель описывающая запись пользователя

    Related:
        - product - to model Product
        - purchases - to model PermanentPurchase

    """
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='Владелец',
        related_name='Content',
        **NULLABLE
    )
    title = models.CharField(max_length=100, verbose_name='заголовок')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(
        upload_to=user_directory_path_content,
        verbose_name='изображение', default=None
    )
    date_update = models.DateTimeField(
        auto_now_add=True,
        verbose_name='дата последнего обновления'
    )
    start_publish = models.DateTimeField(
        default=None,
        verbose_name='Дата и время публикации',
        **NULLABLE
    )
    is_publish = models.BooleanField(
        default=False,
        verbose_name='публичный доступ'
    )
    is_free = models.BooleanField(
        default=True,
        verbose_name='Бесплатный контент'
    )
    is_paid_subs = models.BooleanField(
        default=False,
        verbose_name='Контент в подписке на пользователя'
    )
    is_src_subs = models.BooleanField(
        default=False,
        verbose_name='Контент в подписке на сервис'
    )
    is_purchase = models.BooleanField(
        default=False,
        verbose_name='Доступно для приобретения в коллекцию'
    )
    view_count = models.PositiveIntegerField(
        default=0,
        verbose_name='Количество просмотров'
    )

    def __str__(self):
        return f'{self.title}-{self.owner}'


class Video(models.Model):
    """Модель описывающая видео"""

    content = models.OneToOneField(
        Content,
        on_delete=models.CASCADE,
        verbose_name='контент',
        related_name='video')
    url = models.URLField(verbose_name='ссылка на видео')
    video_id = models.CharField(max_length=150, verbose_name='ID видео',
                                **NULLABLE)

    def __str__(self):
        return f'video to {self.content}'

content/views.py
from django.forms import inlineformset_factory
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.http import Http404
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
    CreateView,
    UpdateView
)

from content.forms import ContentForm, ContentUpdateForm
from content.models import Content

from content.src.src_context import get_index_context, \
    get_content_detail_context, get_formset_to_create
from content.tasks import task_get_image, task_delete_img
from product.forms import ProductForm
from product.models import Product
from product.tasks import task_create_product, task_delete_product


class IndexView(ListView):
    """Вывод главной страницы"""

    model = Content
    template_name = 'content/index.html'

    def get_queryset(self):
        """Переопределение для сбора ограниченного количества видео"""
        if self.request.user.is_authenticated:
            queryset = super().get_queryset().exclude(
                owner=self.request.user).order_by('?').filter(
                is_publish=True)[:12]
        else:
            queryset = super().get_queryset().order_by('?').filter(
                is_publish=True)[:12]

        return queryset

    def get_context_data(self, **kwargs):
        """Переопределение для расширения контекста домашней страницы"""

        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'NewTerra'

        if self.request.user.is_authenticated:
            context_data = get_index_context(
                context_data=context_data, user=self.request.user
            )

        return context_data


class ContentDetailView(DetailView):
    """
    Контроллер для отображения детальной информации об экземпляре контента.
    """
    model = Content

    def get_context_data(self, **kwargs):
        """Переопределение метода для формирования необходимого
        дополнительного контекста"""

        context_data = super().get_context_data(**kwargs)

        context_data = get_content_detail_context(
            context_data=context_data,
            user=self.request.user,
            content=self.object,
        )

        return context_data

    def get_object(self, queryset=None):
        """Переопределение реализует счетчик просмотров"""
        obj = super().get_object(queryset)
        obj.view_count += 1
        obj.save()
        return obj


class ContentListView(LoginRequiredMixin, ListView):
    """Контроллер для отображения списка контента"""

    model = Content
    extra_context = {'title': 'Мой контент'}
    login_url = 'users:login'

    def get_queryset(self):
        """Переопределение для выборки из контента
         принадлежащего пользователю"""
        queryset = super().get_queryset().filter(
            owner=self.request.user).order_by('-date_update')
        return queryset


class ContentCreateView(LoginRequiredMixin, CreateView):
    """Представление для создания контента"""
    model = Content
    form_class = ContentForm
    login_url = 'users:login'
    extra_context = {
        'title': 'Создание контента'
    }

    success_url = reverse_lazy('content:content_list')

    def get_form_kwargs(self, **kwargs):
        """Метод передает авторизованного пользователя в kwargs"""
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        """Переопределение добавляет формсет содержания контента"""

        context_data = super().get_context_data(**kwargs)

        context_data = get_formset_to_create(
            context_data=context_data,
            request=self.request,
            instance=self.object
        )

        return context_data
    
    def form_valid(self, form):
        """Переопределение для добавления владельца и проверки наличия
        обложки видео"""

        product_formset = self.get_context_data()['product_formset']
        video_formset = self.get_context_data()['video_formset']

        if not video_formset.is_valid() or not product_formset.is_valid():
            return self.form_invalid(form)

        if video_formset.is_valid():
            form.instance.owner = self.request.user
            self.object = form.save()

            if not self.object.image:
                task_get_image.delay(pk=self.object.pk)
            video_formset.instance = self.object
            video_formset.save()

            if self.object.is_purchase:
                if product_formset.is_valid():
                    product_formset.instance = self.object
                    product_formset.save()
                    task_create_product.delay(self.object.product.pk)

        return super().form_valid(form)


class ContentUpdateView(LoginRequiredMixin, UpdateView):
    """Представление для обновления контента"""
    model = Content
    form_class = ContentUpdateForm
    login_url = 'users:login'
    extra_context = {
        'title': 'Обновление контента'
    }

    success_url = reverse_lazy('content:content_list')

    def get_form_kwargs(self, **kwargs):
        """Метод передает авторизованного пользователя в kwargs"""
        kwargs = super().get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_success_url(self):
        """Переопределение для перенаправления после редактирования
        контента"""
        return reverse(
            'content:content_detail',
            args=[self.kwargs.get('pk')]
        )

    def get_context_data(self, **kwargs):
        """Переопределение добавляет формсет цены контента"""

        context_data = super().get_context_data(**kwargs)

        formset = inlineformset_factory(Content, Product,
                                        form=ProductForm,
                                        extra=1,
                                        can_delete=False)
        if self.request.method == 'POST':
            product_formset = formset(self.request.POST,
                                      instance=self.object)
        else:
            product_formset = formset(instance=self.object)

        context_data['product_formset'] = product_formset
        return context_data

    def form_valid(self, form):
        """Переопределение для сохранения формсета"""
        formset = self.get_context_data()['product_formset']

        if self.object.is_purchase:
            if not formset.is_valid():
                return self.form_invalid(form)
            if formset.is_valid():
                self.object = form.save()
                formset.instance = self.object
                formset.save()
                task_create_product.delay(self.object.product.pk)
        if self.object.is_free:
            product = Product.objects.filter(content=self.object).first()
            if product:
                task_delete_product.delay(self.object.product.stripe_id)
                product.delete()
        return super().form_valid(form)


class ContentDeleteView(LoginRequiredMixin, DeleteView):
    """Представление для удаления контента"""

    model = Content
    success_url = reverse_lazy('content:content_list')
    login_url = 'users:login'
    extra_context = {
        'title': 'Подтверждение удаления'
    }

    def form_valid(self, form):
        """Переопределение для удаления файлов связанных с контентом"""
        if self.request.user == self.object.owner:
            if self.object.is_purchase:
                task_delete_product.delay(self.object.product.stripe_id)
            if self.object.image:
                task_delete_img.delay(path_to=str(self.object.image))
            return super().form_valid(form)
        raise Http404('Вы не являетесь владельцем данного контента')

content/templates/content/base.html
<!doctype html>
{% load static %}
{% load templatetags %}
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{{ title }}</title>


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-grid.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    {#    <link href="{% static 'css/headers.css' %}" rel="stylesheet">#}
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
</head>
<body>

<main>
    <h1 class="visually-hidden">Headers examples</h1>

    <div class="container " container="body">
        <header class="d-flex flex-wrap justify-content-center justify-content-md-between py-2 mb-4 border-bottom">
            <a href="/"
               class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-primary text-decoration-none">
                <img src="{% mediapath 'default/Logo.png' %}" alt="{% mediapath 'default/Logo.png' %}"
                             width="20" height="20" class="rounded-circle">
                <span class="fs-4">NewTerra</span>
            </a>
{#            <ul class="d-flex nav col-12 col-md-auto mb-3 justify-content-center mb-md-0">#}
{#                <li><a href="#" class="btn btn-success btn-sm rounded rounded-5">Оформить#}
{#                    подписку на сервис</a>#}
{#                </li>#}
{#                <li><a href="#"#}
{#                       class="nav-link px-2 link-primary ">Контент</a>#}
{#                </li>#}
{#                <li><a href="#" class="nav-link px-2 link-primary">Pricing</a>#}
{#                </li>#}
{#                <li><a href="#" class="nav-link px-2 link-primary">FAQs</a>#}
{#                </li>#}
{#                <li><a href="#" class="nav-link px-2 link-primary">About</a>#}
{#                </li>#}
{#            </ul>#}
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                <input type="search" class="form-control"
                       placeholder="Искать..." aria-label="Search">
            </form>

            <div class="dropdown text-end">
                <a href="#"
                   class="d-block link-dark text-decoration-none dropdown-toggle"
                   id="dropdownUser1" data-bs-toggle="dropdown"
                   aria-expanded="false">
                    {% if user.is_authenticated %}
                        <img src="{% mediapath user.avatar %}" alt="{% mediapath 'default/NoneUser.png' %}"
                             width="32" height="32" class="rounded-circle">
                    {% else %}
                        <img src="{% mediapath 'default/NoneUser.png' %}" alt="{% mediapath 'default/NoneUser.png' %}"
                             width="32" height="32" class="rounded-circle">
                    {% endif %}
                </a>
                {% if user.is_authenticated %}
                    <ul class="dropdown-menu text-small"
                        aria-labelledby="dropdownUser1">
                        <h5
                                class="mb-3 text-secondary text-center">{{ user.username }}
                        </h5>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item text-primary"
                               href="{% url 'content:content_create' %}">Добавить
                            видео</a></li>
                        <li><a class="dropdown-item text-primary"
                               href="{% url 'content:content_list' %}">Панель
                            управления</a>
                        </li>
                        <li><a class="dropdown-item text-primary"
                               href="{% url 'users:user_update' %}">
                            Редактировать профиль</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item text-primary"
                               href="{% url 'users:logout' %}">Выход</a>
                        </li>
                    </ul>
                {% else %}
                    <ul class="dropdown-menu text-small"
                        aria-labelledby="dropdownUser1">
                        <li><a class="dropdown-item text-primary"
                               href="{% url 'users:login' %}">Вход</a>
                        </li>
                        <li><a class="dropdown-item text-primary"
                               href="{% url 'users:user_create' %}">Регистрация</a>
                        </li>
                    </ul>
                {% endif %}

            </div>

        </header>
    </div>

    <div class="col-md-9 ms-sm-auto col-lg-12 px-md-4">
        {% block content %}
        {% endblock %}
    </div>

    <div class="container">
        <footer class="py-3 my-1">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            </ul>
            <p class="text-center text-body-secondary">&copy; 2023 Newterra,
                Inc</p>
        </footer>
    </div>


</main>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script></script>
<script src="{% static 'js/main.js' %}"></script>
{#<script src="{% static 'js/feather.min.js' %}"#}
{#        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="{% static 'js/Chart.min.js' %}"#}
{#        integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"#}
{#        crossorigin="anonymous"></script>#}

</body>
</html>

content/templates/content/content_confirm_delete.html
{% extends 'users/base.html' %}
{% load templatetags %}

{% block content %}
    <div>
        <h1 class="h2 mb-3 fw-bold">Вы уверены?</h1>
        <p class="fw-light mb-3 fw-normal">Будет
            удалено: {{ object.title }}.</p>
        {% if object.view_count > 1000 %}
            <p class="fw-light mb-3 fw-normal">"Это видео популярно, оно
                набрало: {{ object.view_count }} просмотров.</p>
        {% endif %}
        <form method="post" enctype="multipart/form-data">
            <div class="d-grid gap-3">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="w-100 btn btn-lg btn-outline-secondary"
                        data-bs-toggle="tooltip"
                        data-bs-placement="right"
                        title="Данное действие невозможно отменить"
                        type="submit">
                    Удалить
                </button>
                <button href="{% url 'content:content_list' %}"
                        class="w-100 btn btn-lg btn-primary">Отмена
                </button>
            </div>
        </form>
    </div>
    <p class="mt-5 mb-3 text-muted">&copy; Newterra.inc 2023</p>
{% endblock %}

content/templates/content/content_detail.html
{% extends 'content/base.html' %}
{% load templatetags %}

{% block content %}
    <div class="container">
        <div class="row row-cols-auto">
            <div class="col-md-8">
                {% include 'subscription/includes/inc_subs_button_detail.html' %}
                <div class="row pt-3">
                    <div class="col-11">
                        <h4 class="gap-3 pt-2">
                            {{ object.title }}
                        </h4>
                    </div>
                    <div class="col-1">
                        <div class="pt-2 d-grid justify-content-end ">
                            <button class="btn btn-outline-primary rounded rounded-5"
                                    type="button">
                                Like
                            </button>
                        </div>
                    </div>
                </div>
                <div class="row pt-2">
                    <div class="col-auto bg-body position-relative">
                        <img src="{% mediapath object.owner.avatar %}"
                             alt="{% mediapath 'default/NoneUser.png' %}"
                             width="40"
                             height="40" class="rounded-circle">
                        <a href="{%  url 'users:user_detail' object.owner.pk %}" class="stretched-link"></a>
                    </div>
                    <div class="col-3">
                        <div class="row g-0 bg-body position-relative">
                            <div class="fs-6 fw-semibold">{{ object.owner.username }}</div>
                            <small class="fw-lighter">Количество подписчиков: {{ sub.subs_count }}
                            </small>
                            <a href="{%  url 'users:user_detail' object.owner.pk %}" class="stretched-link"></a>
                        </div>
                    </div>
                    <div class="col-auto d-md-block">
                        {% if user.is_authenticated %}
                            <div class="d-grid gap-2 d-md-block">
                                {% include 'subscription/includes/inc_subscribe.html' %}
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="rounded-3 bg-light p-3">
                    <p>
                        Опубликовано {{ object.date_update.date }}
                        Просмотров: {{ object.view_count }}
                    </p>
                    <div class="collapse" id="collapseExample">
                        <div class="text">
                            {{ object.description | linebreaksbr | urlizetrunc:40 }}
                        </div>
                    </div>
                    <p>
                        <a class="link-secondary text-md-end"
                           data-bs-toggle="collapse"
                           href="#collapseExample" role="button"
                           aria-expanded="false"
                           aria-controls="collapseExample"
                           data-target="#services"
                           id="show"><span>Описание</span>
                        </a>
                    </p>
                </div>
                <form>
                    <div class="row pt-3 d-flex justify-content-end">
                        <div class="mb-3 col-12">
                            <input type="text" id="disabledTextInput"
                                   class="form-control"
                                   placeholder="Оставьте комментарий...">
                            <a class="link" href="#"></a>
                        </div>
                    </div>
                </form>
                <div>
                    <div class="row pt-3">
                        <div class="col-auto">
                            <img src="https://github.com/mdo.png" alt="{% mediapath 'default/NoneUser.png' %}"
                                 width="32"
                                 height="32" class="rounded-circle">
                        </div>
                        <div class="col-auto g-0 bg-body position-relative">
                            <span class="fw-normal align-bottom">Автор</span>
                            <a href="#" class="stretched-link"></a>
                        </div>
                        <div class="col-auto">
                            <span class="fw-lighter align-bottom">Время</span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-1"></div>
                        <div class="col-11">
                            <p class="fw-light bg-light rounded p-3">
                                Комментарий</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                {% for content in play_list %}
                    <div class="mb-1" href=""
                         style="width: 24rem;">
                        <div class="row bg-body position-relative">
                            <div class="col-md-5 ratio ratio-16x9">
                                <img src="{% mediapath content.image %}"
                                     class="img-fluid rounded"
                                     alt="...">
                            </div>
                            <div class=" flex-column card-img-overlay">
                                {% include 'content/includes/inc_badge.html' %}
                            </div>
                            <div class="col-md-7">
                                <p class="card-title fw-bold ">{{ content.title|truncatechars:35 }}</p>
                                <small class="fw-light">{{ content.owner.username }}</small>
                                <p><small
                                        class="fw-light">{{ content.view_count }}
                                    просмотров</small></p>
                                <a href="{% url 'content:content_detail' content.pk %}"
                                   class="stretched-link"></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

content/templates/content/content_form.html
{% extends 'content/base.html' %}
{% load templatetags %}
{% load crispy_forms_tags %}
{% crispy content_form content.helper %}

{% block content %}
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-6">
                    {% csrf_token %}
                    {{ form | crispy }}
                </div>
                <div class="col-6">
                    {{ video_formset.management_form }}
                    {% for form in video_formset.forms %}
                        {{ form | crispy }}
                    {% endfor %}
                    {{ product_formset.management_form }}

                    {% for form in product_formset.forms %}
                        {{ form | crispy }}
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col-auto">
                    {% if not object.pk %}
                        <button class="btn btn-primary" type="submit">Создать
                        </button>
                    {% else %}
                        <button class="btn btn-primary" type="submit">Обновить
                        </button>
                    {% endif %}
                    <button class="btn btn-outline-dark" type="reset">Отмена
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

content/templates/content/content_list.html
{% extends 'content/base.html' %}
{% load templatetags %}

{% block content %}
    <div class="container gx-5">
        <div class="row row-cols-1 row-cols-md-2 gx-5 gy-2">
            {% for content in object_list %}
                <div class="mb-1" href="">
                    <div class="row bg-body">
                        <div class="col-4 ratio ratio-16x9">
                            <img src="{% mediapath content.image %}"
                                 class="img-fluid rounded"
                                 alt="{% mediapath 'default/download.png' %}">
                            <a href="{% url 'content:content_detail' content.pk %}"
                               class="stretched-link"></a>
                            <div class=" flex-column card-img-overlay">
                                {% include 'content/includes/inc_badge.html' %}
                            </div>
                        </div>
                        <div class="col-5">
                            <p class="card-title fw-bold ">{{ content.title|truncatechars:40 }}</p>
                            <small class="fw-light">{{ content.owner.username }}</small>
                            <p><small
                                    class="fw-light">{{ content.view_count }}
                                просмотров</small></p>
                        </div>
                        <div class="col-3 d-grid gap-1">
                            <a href="{% url 'content:content_update' content.pk %}"
                               class="btn btn-outline-primary btn-sm rounded rounded-5">
                                Редактировать
                            </a>
                            <a class="btn btn-outline-primary btn-sm rounded rounded-5"
                               href="{% url 'content:content_delete' content.pk %}">
                                Скрыть
                            </a>
                            <a class="btn btn-outline-secondary btn-sm rounded rounded-5"
                               href="{% url 'content:content_delete' content.pk %}">
                                Удалить
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center pt-3">
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}