config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('content.urls', namespace='content')),
    path('subscription/', include(
        'subscription.urls',
        namespace='subscription')),
    path('product/', include('product.urls', namespace='product'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/urls.py
from django.urls import path
from content.apps import ContentConfig
from content.views import ContentDetailView, ContentListView, \
    ContentCreateView, ContentUpdateView, IndexView, ContentDeleteView

app_name = ContentConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path(
        'content/<int:pk>/detail/',
        ContentDetailView.as_view(),
        name='content_detail'
    ),
    path(
        'content/',
        ContentListView.as_view(),
        name='content_list'
    ),
    path(
        'content/create/',
        ContentCreateView.as_view(),
        name='content_create'
    ),
    path(
        'content/<int:pk>/update/',
        ContentUpdateView.as_view(),
        name='content_update'
    ),
    path(
        'content/<int:pk>/delete/',
        ContentDeleteView.as_view(),
        name='content_delete'
    )
]

product/urls.py
from django.urls import path
from product.apps import ProductConfig
from product.views import PaymentCreateView, PaymentCheckView

app_name = ProductConfig.name

urlpatterns = [
    path(
        'payment/<int:pk>/check/',
        PaymentCheckView.as_view(),
        name='payment_check'
    ),
    path(
        'product/<int:pk>/payment',
        PaymentCreateView.as_view(),
        name='product_payment'
    ),

]

subscription/urls.py
from subscription.apps import SubscriptionConfig
from django.urls import path

from subscription.views import subscribe

app_name = SubscriptionConfig.name

urlpatterns = [
    path('<int:pk>/subscribe/', subscribe, name='subscribe'),
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import UserRegisterView, LoginView, LogoutView, \
    UserUpdateView, UserDetailView, VerifyView, GetVerify

app_name = UsersConfig.name

urlpatterns = [
    path('<int:pk>/detail/', UserDetailView.as_view(), name='user_detail'),
    path('create/', UserRegisterView.as_view(), name='user_create'),
    path('update/', UserUpdateView.as_view(), name='user_update'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('<int:pk>/verify/', VerifyView.as_view(), name='verify'),
    path('<int:pk>/get/verify/', GetVerify.as_view(), name='get_verify')
]

users/models.py
from random import randint

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


NULLABLE = {
    'null': True,
    'blank': True
}


class UserRoles(models.TextChoices):
    MEMBER = 'member', 'пользователь'
    MODERATOR = 'moderator', 'модератор'


class User(AbstractUser):
    """
    Модель пользователя

    Related:
        - content - to model Content

        - subs - to model Subscription field owner
        - subscribers - to model Subscription field author

        - paid_subs - to model PaidSubscription field owner
        - paid_subscribers - to model PaidSubscription field author

        - src_subs - to model ServiceSubscription field owner

        - purchases - to model PermanentPurchase

        - product_user - to model Product

        - pay - to model Pay

    """

    phone = models.CharField(
        max_length=10,
        verbose_name='Телефон',
        unique=True
    )
    username = models.CharField(
        max_length=30,
        verbose_name='Псевдоним',
        unique=True
    )
    email = models.EmailField(verbose_name=_('email'))
    first_name = models.CharField(
        max_length=50,
        verbose_name='Имя',
        **NULLABLE
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name='Фамилия',
        **NULLABLE
    )
    birthday = models.DateField(
        verbose_name='День рождения',
    )
    is_active = models.BooleanField(
        default=False,
        verbose_name=_('verification status')
    )

    role = models.CharField(
        max_length=20,
        choices=UserRoles.choices,
        default=UserRoles.MEMBER,
        verbose_name=_('role')
    )
    avatar = models.ImageField(
        upload_to='users/avatar/',
        verbose_name='Аватар',
        default='default_avatar.jpg'
    )

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return f'user_{self.pk}'


class Verify(models.Model):
    """
    Модель для проверки кода верификации пользователя
    """
    user_code = models.PositiveIntegerField(
        verbose_name='user code',
        **NULLABLE)
    verify_code = models.PositiveIntegerField(
        verbose_name='verify code')
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name='user',
        related_name='verify'
    )

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, \
    UsernameField, UserChangeForm
from django import forms

from content.forms import StyleMixin
from users.models import User, Verify


class RegisterForm(StyleMixin, UserCreationForm):
    """Форма для регистрации нового пользователя"""

    birthday = forms.DateField(
        label="Дата рождения",
        widget=forms.DateInput(
            attrs={'type': 'date'},
        ),
        required=True
    )

    phone = forms.CharField(
        label="Номер",
        widget=forms.TextInput(
            attrs={'class': '"col-form-label"',
                   'type': 'text',
                   'id': 'addon-wrapping',
                   'placeholder': '10 цифр без +7'},
        ),
        max_length=10,
        required=True
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = (
            'phone',
            'password1',
            'password2',
            'email',
            'username',
            'first_name',
            'last_name',
            'birthday',
            'avatar',
        )


class UserUpdateForm(StyleMixin, UserChangeForm):
    """Форма для обновления профиля пользователя"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',
            'avatar',
        )


class LoginForm(StyleMixin, AuthenticationForm):
    username = UsernameField(
        label='',
        widget=forms.TextInput(
            attrs={"autofocus": True,
                   'placeholder': '10 цифр без +7',
                   'type': 'phone'
                   }))
    password = forms.CharField(
        label='',
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password",
                   'placeholder': 'Пароль'}
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)


class VerifyForm(forms.ModelForm):

    user_code = forms.CharField(
        label="",
        widget=forms.TextInput(
            attrs={'class': 'form-control',
                   'type': 'text',
                   'id': 'addon-wrapping',
                   'placeholder': '0000'},
        ),
        help_text='Сейчас вам поступит звонок, введите последние 4 цифры '
                  'номера звонящего',
        max_length=4,
        required=True
    )

    class Meta:
        model = Verify
        fields = 'user_code',

    def clean(self):
        """Метод проверяет правильность введенного пользователем кода"""

        cleaned_data = super().clean()
        user_code = cleaned_data.get('user_code')
        if int(user_code) != self.instance.verify_code:
            raise forms.ValidationError('Неверный код')

        return cleaned_data

users/views.py
from django.contrib.auth.views import LoginView as BaseLoginView, \
    LogoutView as BaselogoutView
from django.views.generic import CreateView, UpdateView, TemplateView
from django.forms import inlineformset_factory
from django.db.models import Sum
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse

from content.models import Content
from product.forms import UserProductForm
from product.models import Product
from subscription.models import Subscription
from subscription.src.subscription import WorkSubscription
from users.forms import RegisterForm, LoginForm, UserUpdateForm, VerifyForm
from users.models import User, Verify
from users.services import get_client_ip
from users.src.smsru_api import APISMSru


class UserFormsetMixin:
    """Миксин с переопределением методов представлений"""

    def get_context_data(self, **kwargs):
        """Переопределение добавляет формсет создания продукта пользователя"""

        context_data = super().get_context_data(**kwargs)
        formset = inlineformset_factory(User, Product,
                                        form=UserProductForm,
                                        extra=1,
                                        can_delete=False)

        if self.request.method == 'POST':
            formset = formset(self.request.POST,
                              instance=self.object)
        else:
            formset = formset(instance=self.object)

        context_data['formset'] = formset
        return context_data

    def form_valid(self, form):
        """Переопределнние для валидации и сохранения формсета"""

        formset = self.get_context_data()['formset']

        if not formset.is_valid():
            return self.form_invalid(form)

        self.object = form.save()
        formset.instance = self.object
        formset.save()

        return super().form_valid(form)


class UserDetailView(TemplateView):
    """Представление детальной информации о пользователе"""
    template_name = 'users/user_detail.html'

    def get_context_data(self, **kwargs):
        """Переопределение для вывода дополнительного контекста"""

        context_data = super().get_context_data(**kwargs)

        # Получаем основной объект
        author = User.objects.get(pk=self.kwargs.get('pk'))
        context_data['author'] = author

        # Получаем контент автора
        context_data['content_list'] = Content.objects.filter(
            owner=author, is_publish=True).order_by('-date_update')

        # Собираем сопутствующий контент
        product = Product.objects.filter(user=author).first()
        sub = {
            'subs_count': Subscription.objects.filter(
                author=author).count(),
            'view_count': Content.objects.values('view_count').filter(
                owner=author, is_publish=True).aggregate(
                Sum('view_count'))['view_count__sum'],
            'video_count': len(context_data['content_list']),
            'paid_subs_price': product.price if product else None,
            'paid_subs_currency':
                product.get_currency_display() if product else None,
            'paid_subs_pk': product.pk if product else None
        }
        context_data['sub'] = sub

        # проверяем подписки пользователя
        if self.request.user.is_authenticated:
            context_data['subs'] = WorkSubscription.subs_status(
                        self.request.user,
                        author,
                    )
        return context_data


class UserRegisterView(UserFormsetMixin, CreateView):
    """Представление регистрации пользователя"""
    model = User
    form_class = RegisterForm

    success_url = reverse_lazy('content:content_list')

    def form_valid(self, form):
        """Переопределнние для валидации и сохранения формсета"""

        formset = self.get_context_data()['formset']

        if not formset.is_valid():
            return self.form_invalid(form)
        self.object = form.save(commit=False)
        ip = get_client_ip(self.request)
        verify_code = APISMSru().get_verify_code(
            phone=f'7{self.object.phone}',
            ip_address=ip
        )
        print(verify_code)
        if not verify_code:
            return redirect(reverse(
                'content:index'))
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        verify = Verify.objects.create(
            user=self.object, verify_code=verify_code)
        verify.save()
        return redirect(reverse(
            'users:verify', args=[verify.pk]))


class UserUpdateView(UserFormsetMixin, UpdateView):
    """Представление для редактирования профиля пользователя"""

    model = User
    form_class = UserUpdateForm

    success_url = reverse_lazy('content:index')

    def get_object(self, queryset=None):
        return self.request.user


class LoginView(BaseLoginView):
    """Класс для представления авторизации пользователя"""
    form_class = LoginForm
    template_name = 'users/login.html'


class LogoutView(BaselogoutView):
    """Класс для представления выхода пользователя"""
    pass


class VerifyView(UpdateView):
    """Представление проверки кода верификации"""
    model = Verify
    success_url = 'users:login'
    form_class = VerifyForm

    def form_valid(self, form):
        """Переопределение делает пользователя которому принадлежит код
        верификации активным"""

        self.object = form.save()
        user = self.object.user
        user.is_active = True
        user.save()
        self.object.delete()
        return redirect(reverse(self.success_url))


class GetVerify(TemplateView):
    """Представление для повторного запроса кода верификации"""
    model = Verify
    success_url = 'users:verify'

    def get(self, request, *args, **kwargs):

        verify = Verify.objects.get(pk=self.kwargs.get('pk'))
        user = verify.user
        ip = get_client_ip(self.request)
        verify_code = APISMSru().get_verify_code(
            phone=f'7{user.phone}',
            ip_address=ip
        )
        verify.verify_code = verify_code
        verify.save()
        return redirect(reverse(
            'users:verify', args=[verify.pk]))

users/templates/users/base.html
{% load templatetags %}
{% load static %}

<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <meta name="theme-color" content="#7952b3">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">
</head>
<body class="text-center">

<main class="form-signin">
    {% block content %}
    {% endblock %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</main>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load templatetags %}
{% load crispy_forms_tags %}
{% crispy login login.helper %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="position-relative">
            <img class="img" src="{% mediapath 'default/Logo.png' %}"
                 alt="" width="72" height="72">
            <a href="{% url 'content:index' %}" class="stretched-link"></a>
        </div>
        <h1 class="h3 mb-3 fw-normal pt-3">Пожалуйста, войдите</h1>
        {% csrf_token %}
        {{ form|crispy }}

        <button class="w-100 btn btn-lg btn-primary" type="submit">Войти
        </button>
    </form>
    <a class="link p-3"
           href="{% url 'users:user_create' %}">Зарегистрироваться</a>
        <p class="mt-5 mb-3 text-muted">&copy; Newterra.inc 2023</p>
{% endblock %}

users/templates/users/user_detail.html
{% extends 'content/base.html' %}
{% load templatetags %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-11">
                <h4 class="card-title text-end text-primary">{{ author.username | upper }}</h4>
                <div class="text-md-end">
                    <span class="badge badge-end rounded-pill bg-success">ПОДПИСАНО {{ sub.subs_count }}</span>
                    <span class="badge badge-end rounded-pill bg-primary">ПРОСМОТРОВ {{ sub.view_count }}</span>
                    <span class="badge badge-end rounded-pill bg-info">ОПУБЛИКОВАНО ВИДЕО {{ sub.video_count }}</span>
                </div>
                <div class="text-end pt-2">
                    {% if subs.paid_subs %}
                        <span class="badge rounded-pill bg-primary">Платная подписка истечет</span>
                    {% elif user.pk == author.pk %}
                        <span class="badge rounded-pill bg-primary">ЭТО ВАШ ПРОФИЛЬ</span>
                    {% else %}
                        {% if user.is_authenticated %}
                            <form action="{% url 'subscription:subscribe' author.pk %}"
                                  method="GET" id="ajax_subscribe">
                            {% csrf_token %}
                            {% if subs.subs %}
                                <input class="btn btn-sm btn-primary rounded rounded-4"
                                       type="submit" id="subs"
                                       value="Отписаться"
                                >
                            {% else %}
                                <input class="btn btn-sm btn-primary rounded rounded-4"
                                       type="submit"
                                       value="Подписаться бесплатно"
                                       id="subs">
                            {% endif %}
                            {% if sub.paid_subs_price %}
                                <a class="btn btn-sm btn-danger rounded rounded-4"
                                   href="{% url 'product:product_payment' sub.paid_subs_pk %}">Подписаться
                                    за
                                    {{ sub.paid_subs_price }}{{ sub.paid_subs_currency }}</a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                    </form>
                </div>
            </div>
            <div class="col-md-auto">
                <img src="{% mediapath author.avatar %}"
                     alt="{% mediapath 'default/NoneUser.png' %}"
                     width="50"
                     height="50" class="rounded-circle text-end">
            </div>
        </div>
    </div>
    </div>
    <div class="container pt-3">
        <div class="row row-cols-1 row-cols-md-4 g-3">
            {% for content in content_list %}
                {% include 'content/includes/inc_video_block.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'content/base.html' %}
{% load templatetags %}
{% load crispy_forms_tags %}
{% crispy user_form content.helper %}

{% block content %}
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-6">
                    {% csrf_token %}
                    {{ form | crispy }}
                </div>
                <div class="col-6">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form | crispy }}
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col-auto">
                    {% if user.is_authenticated %}
                        <button class="btn btn-primary" type="submit">Обновить
                    </button>
                    {% else %}
                        <button class="btn btn-primary" type="submit">Создать
                        </button>
                    {% endif %}
                    <button class="btn btn-outline-dark" href="{% url 'content:index' %}">Отмена
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/verify_form.html
{% extends 'users/base.html' %}
{% load templatetags %}
{% load crispy_forms_tags %}
{% crispy login login.helper %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        <div class="position-relative">
            <img class="img" src="{% mediapath 'default/Logo.png' %}"
                 alt="" width="72" height="72">
            <a href="{% url 'content:index' %}" class="stretched-link"></a>
        </div>
        <h1 class="h3 mb-3 fw-normal">Подтвердите номер телефона</h1>
        {% csrf_token %}
        {{ form|crispy }}

        <button class="w-100 btn btn-lg btn-primary" type="submit">Подтвердить
        </button>
    </form>
    <a class="link p-3"
       href="{% url 'users:get_verify' object.pk %}">Запросить код
        повторно</a>
    <p class="mt-5 mb-3 text-muted">&copy; Newterra.inc 2023</p>
{% endblock %}